# version: '3.8'

# services:
#   agent4_bos:
#     build: .
#     container_name: agent4_bos
#     ports:
#       - "8004:8000"
#     networks:
#       - ai_network
#     environment:
#       - COLLECTION=agent4_bos_cases
#       - QDRANT_HOST=qdrant
#       - QDRANT_PORT=6333
# networks:
#   ai_network:
#     external: true

version: '3.8'

services:
  agent4_bos:
    build: .
    container_name: agent4_bos
    ports:
      - "8004:8000"
    volumes:
      - ../../qdrant_data:/app/qdrant_data
    networks:
      - ai_network
    environment:
      - COLLECTION=agent4_bos_cases
      - SPECIAL_CASES_COLLECTION=agent4_bos_cases
      - KNOWLEDGE_BASE_COLLECTION=agent4_knowledge_base
      - BASE_DATA_PATH=/app/qdrant_data
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    command: python main.py

networks:
  ai_network:
    external: true