version: '3.8'

services:
  agent4_bos:
    build: .
    container_name: agent4_bos
    ports:
      - "8004:8000"
    networks:
      - ai_network
    environment:
      - COLLECTION=collection_documents
      - QDRANT_URL=http://qdrant:6333
      - EMBED_MODEL=nomic-embed-text
    volumes:
      - ../../qdrant_data/documents:/qdrant_data/documents
      - ../../qdrant_data/special_cases:/qdrant_data/special_cases
networks:
  ai_network:
    external: true

volumes:
  qdrant_data:
    external: true
